server:
  port: 8082
spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
salesdata-service:
  ribbon:
    listOfServers: localhost:8092
