server:
  port: 8092
spring:
  application:
    name: salesdata-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           
    platform: h2                        
    schema: classpath:schema.sql        
    data: classpath:data.sql            
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    
## INFO
